name: CI

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: test_db
      DB_USERNAME: glucy
      DB_PASSWORD: postgres

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: glucy
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, pdo_pgsql, exif, pcntl, bcmath, gd, zip
          coverage: none

      - name: Cache de dependencias Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Instalar dependencias
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Copiar .env
        run: cp .env.example .env

      - name: Generar app key
        run: php artisan key:generate

      - name: Ejecutar migraciones
        run: php artisan migrate --force

      - name: Lint (Laravel Pint)
        run: vendor/bin/pint --test

      - name: Ejecutar tests
        run: php artisan test