name: CI

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  packages: write
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: test_db
      DB_USERNAME: glucy
      DB_PASSWORD: secret

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: glucy
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, pdo_mysql, exif, pcntl, bcmath, gd, zip
          coverage: none

      - name: Cache de dependencias Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Instalar dependencias
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Copiar .env
        run: cp .env.example .env

      - name: Generar app key
        run: php artisan key:generate

      - name: Ejecutar migraciones
        run: php artisan migrate --force

      - name: Lint (Laravel Pint)
        run: vendor/bin/pint --test

      - name: Ejecutar tests
        run: php artisan test
      
      - name: Login to Github Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor}}
            password: ${{ secrets.GITHUB_TOKEN}}

      - name: Build and push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/benjaminheredia1/glucyback:latest
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Disparar en Dokploy
        run: |
          curl -X POST "${{ secrets.DOKPLOY_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            --fail --silent --show-error
